version: "3.5"
services:
  app-postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app
networks:
  app:
