service: ${env:SERVICE_NAME, 'anonymous-lambda'}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_S3_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}

functions:
  example-lambda:
    handler: lambdas/example-lambda/handler.handle
    environment:
      APP_NAME: ${env:APP_NAME} 
    events:
      - http:
          path: /
          method: GET
