service: ${env:SERVICE_NAME, 'anonymous-lambda'}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-log-retention

package:
  individually: true

custom:
  logRetentionInDays: 30
  serverless-offline:
    useChildProcesses: true
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_S3_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30

functions:
  example-lambda:
    handler: lambdas/example-lambda/handler.handle
    environment:
      APP_NAME: ${env:APP_NAME}
    events:
      - http:
          path: /
          method: GET
  # PLOP_ADD_LAMBDA
